# Generated by Django 4.1 on 2022-08-22 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_place_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
