# Generated by Django 4.1 on 2022-08-26 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_place_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
